### In this notebook, we're going to cover some of the fundamentals of tensorflow

#### More specifically, we're going to cover:
1. Introduction to tensors.
2. Getting information from tensors.
3. Manipulating tensors.
4. Tensors and Numpy.
5. Using @tf.function (a way to speed up your regular Python functions).
6. Using Gpu with tensorflow (or TPUs).
7. Exercises to try your self!.


### Introduction to Tensors

In [2]:
# import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [3]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimension of the tensor.
scalar.ndim

0

In [5]:
# create a vector
vector = tf.constant([10, 10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the number of dimension of the vector
vector.ndim

1

In [7]:
# create a matrix (has more than one dimension)
matrix = tf.constant([[21,2],
                      [2,21]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21,  2],
       [ 2, 21]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# create another matrix 
another_matrix = tf.constant([[21.,2.],
                             [20.,2.],
                             [23.,1.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[21.,  2.],
       [20.,  2.],
       [23.,  1.]], dtype=float16)>

In [10]:
# what's the number dimension of the another_matrix?
another_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

### What we've created so far:
* Scalar: a single number.
* Vector: a number with direction (e.g wind speed and direction).
* Matrix: a 2-dimensional array of numbers.
* Tensor: an n-dimensional array of number (when n can be any number)

### Creating tensors with `tf.Variable`

In [13]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([21,2])
unchangeable_tensor = tf.constant([21,2])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([21,  2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([21,  2], dtype=int32)>)

In [14]:
# Let's try change one of the element in the changeable_tensor
# changeable_tensor[0] = 23
# changeable_tensor

In [15]:
## How about .assign()
changeable_tensor[0].assign(23)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([23,  2], dtype=int32)>

In [16]:
changeable_tensor.assign([21,2001])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([  21, 2001], dtype=int32)>

### Creating random tensors

In [17]:
random_tensor = tf.random.uniform(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.49979556, 0.11812389],
       [0.3187127 , 0.22737586],
       [0.92536795, 0.80255055]], dtype=float32)>

In [18]:
### Create two random (but the same)
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [19]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [20]:
## Are they equal?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [21]:
# Shuffle a tensor
# Valuable for when you want to shuffler the data so the inherent oreder doen't affects learning)
not_shuffled = tf.constant([[21, 2],
                            [23, 9],
                            [28, 30]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21,  2],
       [23,  9],
       [28, 30]], dtype=int32)>

In [22]:
# get different results even thought we set the seed
tf.random.shuffle(
    not_shuffled,
    seed = 2  
)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21,  2],
       [23,  9],
       [28, 30]], dtype=int32)>

In [23]:
# get the same results when we set the seed
tf.random.set_seed(42)
tf.random.shuffle(
    not_shuffled,
    seed = 42  
)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[21,  2],
       [23,  9],
       [28, 30]], dtype=int32)>

**Exercise:** read documentation
https://www.tensorflow.org/api_docs/python/tf/random/set_seed
practice writing 5 random tensors and shuffle them

### It looks like if we want our shuffled to be the same order, we've got to use the global level random seed as well as the operation level random seed:
> Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

### Other ways to make tensor

In [24]:
tf.ones((10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into tensor
The main different between a tensor and Numpy array is that a tensor can be run on GPUs (or TPUs) 

In [26]:
import numpy as np 

In [27]:
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A
# x = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
 A = tf.constant(numpy_A)
 B = tf.constant(numpy_A, shape=(2,3,4))
 A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Getting information from tensor

- Shape: The length (number of elements) of each of dimension of a tensor

In [29]:
print(f"Tensor A shape: {A.shape}")
print(f"Tensor B shape: {B.shape}")

Tensor A shape: (24,)
Tensor B shape: (2, 3, 4)


- Rank: The number of dimension:
  - Scalar: rank 0.
  - Vector: rank 1.
  - Matrix: rank 2.
  - Tensor: rank n.

In [30]:
print(f"Tensor A rank:{A.ndim}")
print(f"Tensor B rank:{B.ndim}")

Tensor A rank:1
Tensor B rank:3


- Axis of dimension: A particular dimension of a tensor

In [31]:
B[:, 1], B[0]

(<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=int32)>)

- Size: The total number of items in the tensor

In [32]:
print(f"A tensor size: {tf.size(A)}")
print(f"B tensor size: {tf.size(B)}")

A tensor size: 24
B tensor size: 24


In [33]:
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [35]:
# get various attributes of our tensor
print('Datatype of every element: ', rank_4_tensor.dtype)
print('Number of dimension (rank): ', rank_4_tensor.ndim)
print('Shape of the tensor: ', rank_4_tensor.shape)
print('Elements along the 0 axis: ', rank_4_tensor.shape[0])
print('Elements along the last axis: ', rank_4_tensor.shape[-1])
print('Total number of elements in the tensor: ', tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimension (rank):  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in the tensor:  120


### Indexing tensor

In [36]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
rank_2_tensor = tf.constant([[21,2],
                             [23,2]])

In [38]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21,  2],
       [23,  2]], dtype=int32)>

In [39]:
# get the last item of each of rank 2
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

### Expand the tensor

- using `tf.newaxis`

In [40]:
# add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[21],
        [ 2]],

       [[23],
        [ 2]]], dtype=int32)>

In [41]:
rank_2_tensor[:,tf.newaxis,:]

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[21,  2]],

       [[23,  2]]], dtype=int32)>

In [42]:
rank_2_tensor[tf.newaxis,...]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[21,  2],
        [23,  2]]], dtype=int32)>

- using `tf.expand_dims`

In [43]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[21,  2]],

       [[23,  2]]], dtype=int32)>

### Manipulate Tensors (Tensor operations)
**Basic operations**

`+`,`-`,`*`,`/`

In [44]:
tensor = tf.constant([[21,2],
                      [23,28]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 12],
       [33, 38]], dtype=int32)>

In [45]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[210,  20],
       [230, 280]], dtype=int32)>

In [46]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, -8],
       [13, 18]], dtype=int32)>

In [47]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10.5,  1. ],
       [11.5, 14. ]])>

- Or using build in function

In [48]:
tf.math.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[210,  20],
       [230, 280]], dtype=int32)>

In [49]:
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 12],
       [33, 38]], dtype=int32)>

### Matrix Multiplication
**Important**

In [50]:
print(tensor)

tf.Tensor(
[[21  2]
 [23 28]], shape=(2, 2), dtype=int32)


In [51]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 487,   98],
       [1127,  830]], dtype=int32)>

In [52]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[441,   4],
       [529, 784]], dtype=int32)>

In [53]:
# matrix mutlipcation with @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 487,   98],
       [1127,  830]], dtype=int32)>

### Rules:
- Number of the inside must match.
- The results is the same as outside 
e.g : 3x3 . 3x2 -> 3.2

In [54]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [4, 5]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [55]:
X, tf.reshape(Y, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [56]:
# X @ Y

In [57]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 30, 33],
       [61, 68, 75],
       [78, 87, 96]], dtype=int32)>

In [58]:
# or the transpose
X, tf.transpose(X), tf.reshape(X, shape=(3,2))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 4],
        [2, 4, 5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>)

**The dot product**
Matrix multiplication is also referred to as dot product
* `tf.matmul()`
* `tf.tensordot()`

In [59]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [60]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 78,  86],
       [105, 116]], dtype=int32)>

### Changing the datatype of the tensor
https://www.tensorflow.org/guide/mixed_precision

In [61]:
# create a new tensor with a default datatype
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [62]:
C = tf.constant([21, 2])
C.dtype

tf.int32

- Change from float32 to float16 (reduce precision)
  - reduce memory and faster computing

In [63]:
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [64]:
# change from int32 to int16
E = tf.cast(C, dtype=tf.int16)
E

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([21,  2], dtype=int16)>

### Aggregating Tensor
Aggregating tensor = condensing them from multiple values down to a smaller amount of values

In [65]:
# Get the absolute values
D = tf.constant([-21, -2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-21,  -2], dtype=int32)>

In [66]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([21,  2], dtype=int32)>

- Get the minimum
- Get the maximum
- Get the mean
- Get the sum

In [67]:
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-21>

In [68]:
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-2>

In [69]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-11>

In [70]:
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-23>

In [71]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([71, 66, 82, 48, 65, 21, 79, 67, 28, 79, 51, 86, 46, 14, 87, 22, 80,
       76, 62, 17, 70, 85, 53, 82, 58, 72, 33, 41, 51, 96, 51, 63, 56, 98,
       68, 25, 41, 48, 65, 46, 47, 59, 35, 60, 12, 68, 17, 34, 80, 25])>

In [72]:
print(f"The minimum value: {tf.reduce_min(E)}")
print(f"The maximum value: {tf.reduce_max(E)}")
print(f"The meam value: {tf.reduce_mean(E)}")
print(f"The sum value: {tf.reduce_sum(E)}")

The minimum value: 12
The maximum value: 98
The meam value: 55
The sum value: 2786


***Exercise:*** Calculating variance and standard deviation 

- Using math:

- [Squaring deviation from the mean] ÷ number of observations = Variance

In [73]:
variance = 0
mean = tf.reduce_mean(E)
for value in E:
  variance += (value-mean)**2
variance /= len(E)
print(variance)

tf.Tensor(514.76, shape=(), dtype=float64)


In [74]:
# tf.math.reduce_variance(E, 1) # won't work` because it's required the tensor dtype is real number
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=514.0>

In [75]:
import tensorflow_probability as tfp

In [76]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=514>

- Sqrt(Variance) = Standard Deviation

In [77]:
standard_deviation = variance**(1/2)
print(standard_deviation)

tf.Tensor(22.688322987827902, shape=(), dtype=float64)


In [78]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=22.67>

In [79]:
tfp.stats.stddev(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=22.67>

### Find the positional maximum and minimum

In [80]:
# Create a new tensor for finding and positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [81]:
# find the positional max value
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [82]:
F[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [83]:
F[tf.argmax(F)] == 0.9671384

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [84]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))

In [85]:
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [86]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [87]:
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [88]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo i love big tiddy",off_value="man, i am such a weabu")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love big tiddy', b'man, i am such a weabu',
        b'man, i am such a weabu', b'man, i am such a weabu'],
       [b'man, i am such a weabu', b'yo i love big tiddy',
        b'man, i am such a weabu', b'man, i am such a weabu'],
       [b'man, i am such a weabu', b'man, i am such a weabu',
        b'yo i love big tiddy', b'man, i am such a weabu'],
       [b'man, i am such a weabu', b'man, i am such a weabu',
        b'man, i am such a weabu', b'yo i love big tiddy']], dtype=object)>

### Squaring, log, square root

In [89]:
# create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [90]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [91]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [92]:
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and Numpy

In [93]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [94]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [95]:
# conver tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [96]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 9.]))
tensor_J = tf.constant([3., 7., 9.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [97]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [98]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [99]:
!nvidia-smi

Tue Jul 13 14:50:23 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    31W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Extra exercise

In [103]:
scalar = tf.constant(21)
vector = tf.constant([21,2])
matrix = tf.constant([[21,2],
                      [23,2]])
tensor = tf.constant([[[21,2],
                      [23,2]],
                      [[28,6],
                      [25,11]]])

In [108]:
tf.random.set_seed(42)
random_t1 = tf.random.uniform(shape=(5,300),minval=0,maxval=1)
random_t2 = tf.random.uniform(shape=(5,300),minval=0,maxval=1)

In [109]:
random_t1,random_t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [110]:
random_t1 * random_t2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[4.57146466e-01, 2.13658452e-01, 3.28531623e-01, ...,
        2.17384368e-01, 2.51955122e-01, 3.40777524e-02],
       [1.45614594e-01, 3.09705492e-02, 6.57417625e-02, ...,
        2.36865208e-01, 9.56212804e-02, 1.13281950e-01],
       [7.73395528e-04, 1.34753399e-02, 7.99194753e-01, ...,
        1.22185037e-01, 4.81487900e-01, 7.18945917e-03],
       [6.55430436e-01, 5.76979630e-02, 9.58052557e-03, ...,
        6.53199196e-01, 5.08804396e-02, 7.79080987e-01],
       [5.81960231e-02, 1.10622704e-01, 2.62571156e-01, ...,
        6.09022558e-01, 1.02241419e-01, 1.14069067e-01]], dtype=float32)>

In [112]:
random_t1 @ tf.transpose(random_t2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
       [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
       [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
       [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
       [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [114]:
random_tensor = tf.random.uniform(([224, 224, 3]), 0, 1)

In [115]:
random_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

In [122]:
# print(f"max values in the first axis: {tf.reduce_max(random_tensor,axis=1)}")
# print(f"min values in the first axis: {tf.reduce_min(random_tensor,axis=1)}")

print(f"max values in the first axis: {tf.reduce_max(random_tensor[0])}")
print(f"min values in the first axis: {tf.reduce_min(random_tensor[0])}")

max values in the first axis: 0.9982912540435791
min values in the first axis: 0.005321383476257324


In [123]:
tensor = tf.constant(tf.random.uniform(shape=[224,224,3]), shape=([1,224,224,3]))

In [124]:
tensor.shape

TensorShape([1, 224, 224, 3])

In [125]:
squeezed_tensor = tf.squeeze(tensor)
squeezed_tensor.shape

TensorShape([224, 224, 3])

In [130]:
random_tensor = tf.random.uniform([10],1,10, dtype=tf.int32)
random_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([7, 3, 8, 5, 1, 3, 9, 4, 4, 1], dtype=int32)>

In [131]:
tf.reduce_max(random_tensor), tf.argmax(random_tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int64, numpy=6>)

In [132]:
# one hot encoding
one_hot_tensor = tf.one_hot(random_tensor, depth=10)
one_hot_tensor

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>